/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Prabhashi
 */
public class MainInterface extends javax.swing.JFrame {

    final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");


    private String query;
    private PreparedStatement statement;
    private ResultSet result;

    private static CardLayout card;
    private final PatientRegistrationPanel patientRegistrationPanel;
    private final PatientInfoPanel patientInfoPanel;
    private final PatientCheckoutPanel patientCheckoutPanel;
    
    /**
     * Creates new form FrameMain
     */
    public MainInterface() {
        initComponents();
        
      
        
        patientRegistrationPanel = new PatientRegistrationPanel();
        jPanelCard.add(patientRegistrationPanel, "jPanelPatientReg");

        patientInfoPanel = new PatientInfoPanel();
        jPanelCard.add(patientInfoPanel, "jPanelPatientInfo");
        
        patientCheckoutPanel = new PatientCheckoutPanel();
        jPanelCard.add(patientCheckoutPanel, "jPanelPatientCheckout");
        
        
        card = (CardLayout) jPanelCard.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonPatientReg = new javax.swing.JButton();
        jButtonPatientInfo = new javax.swing.JButton();
        jButtonPatientCheckout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jPanelCard = new javax.swing.JPanel();
        jPanelDefault = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(getBackground());

        jPanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanelMenu.setAlignmentX(0.0F);
        jPanelMenu.setOpaque(false);

        jButtonPatientReg.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButtonPatientReg.setText("Patient Registration");
        jButtonPatientReg.setAlignmentX(0.5F);
        jButtonPatientReg.setBorder(null);
        jButtonPatientReg.setPreferredSize(new java.awt.Dimension(121, 23));
        jButtonPatientReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientRegActionPerformed(evt);
            }
        });

        jButtonPatientInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButtonPatientInfo.setText("Patient Information");
        jButtonPatientInfo.setBorder(null);
        jButtonPatientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientInfoActionPerformed(evt);
            }
        });

        jButtonPatientCheckout.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButtonPatientCheckout.setText("Patient Checkout");
        jButtonPatientCheckout.setBorder(null);
        jButtonPatientCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientCheckoutActionPerformed(evt);
            }
        });

        home.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home(evt);
            }
        });

        close.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPatientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPatientCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonPatientReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonPatientReg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPatientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPatientCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home)
                    .addComponent(close))
                .addContainerGap())
        );

        jPanelCard.setOpaque(false);
        jPanelCard.setPreferredSize(new java.awt.Dimension(740, 510));
        jPanelCard.setLayout(new java.awt.CardLayout());

        jPanelDefault.setOpaque(false);
        jPanelDefault.setPreferredSize(new java.awt.Dimension(740, 480));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/social-doctor-checking-up-on-a-patient.png"))); // NOI18N
        jLabel1.setText("BRANFORD Hospital ");

        javax.swing.GroupLayout jPanelDefaultLayout = new javax.swing.GroupLayout(jPanelDefault);
        jPanelDefault.setLayout(jPanelDefaultLayout);
        jPanelDefaultLayout.setHorizontalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDefaultLayout.setVerticalGroup(
            jPanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefaultLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanelCard.add(jPanelDefault, "jPanelDefault");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPatientRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientRegActionPerformed

        card.show(jPanelCard, "jPanelPatientReg");      
        
      

    }//GEN-LAST:event_jButtonPatientRegActionPerformed

    private void jButtonPatientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientInfoActionPerformed

        card.show(jPanelCard, "jPanelPatientInfo");
        patientInfoPanel.resetFormEdit();

        patientInfoPanel.setJFormattedTextFieldEditID("");
        patientInfoPanel.setJComboBoxNameEditIndex(-1);
        


    }//GEN-LAST:event_jButtonPatientInfoActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeActionPerformed

    private void jButtonPatientCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientCheckoutActionPerformed
        card.show(jPanelCard, "jPanelPatientCheckout");
         patientCheckoutPanel.resetFormEdit();
         patientCheckoutPanel.resetFormCheckout();
        
    }//GEN-LAST:event_jButtonPatientCheckoutActionPerformed

    private void home(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home
        // TODO add your handling code here:
        MainInterface.setDefaultLayout();
    }//GEN-LAST:event_home


    protected static void setDefaultLayout() {
        card.show(jPanelCard, "jPanelDefault");
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton home;
    private javax.swing.JButton jButtonPatientCheckout;
    private javax.swing.JButton jButtonPatientInfo;
    private javax.swing.JButton jButtonPatientReg;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JPanel jPanelCard;
    private javax.swing.JPanel jPanelDefault;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
